---
name: Baby Buddy (TallTechDude)
version: 1.13.2.6
homeassistant: 2022.7.7
slug: baby_buddy_ttd
description: Track sleep, feedings, diaper changes, tummy time and more!
url: https://github.com/talltechdude/addon-babybuddy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
panel_icon: hass:baby-bottle
ingress: true
ingress_port: 1337
ingress_stream: false
panel_admin: false
options:
  CSRF_TRUSTED_ORIGINS: ""
  NAP_START_MIN: "06:00"
  NAP_START_MAX: "18:00"
  USE_24_HOUR_TIME_FORMAT: False
  INGRESS_USER: ""  
  log_level: info
schema: 
  CSRF_TRUSTED_ORIGINS: str
  NAP_START_MIN: str
  NAP_START_MAX: str
  USE_24_HOUR_TIME_FORMAT: bool
  INGRESS_USER: str  
  log_level: list(debug|info|warning|error|critical)
ports:
  8000/tcp: null
ports_description:
  8000/tcp: Web interface (Not required for Ingress)
